//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 09:04:12 AM EEST 
//


package eu.europa.ec.learningopportunities.v0_5_10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}CourseLocationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}CourseAddress" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}SpecialArrangements" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseLocationInfo",
    "courseAddress",
    "specialArrangements"
})
@XmlRootElement(name = "CourseLocation")
public class CourseLocation {

    @XmlElement(name = "CourseLocationInfo")
    protected List<I18NString> courseLocationInfo;
    @XmlElement(name = "CourseAddress", required = true)
    protected List<I18NString> courseAddress;
    @XmlElement(name = "SpecialArrangements")
    protected List<I18NString> specialArrangements;

    /**
     * Gets the value of the courseLocationInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the courseLocationInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourseLocationInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getCourseLocationInfo() {
        if (courseLocationInfo == null) {
            courseLocationInfo = new ArrayList<I18NString>();
        }
        return this.courseLocationInfo;
    }

    /**
     * Gets the value of the courseAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the courseAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourseAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getCourseAddress() {
        if (courseAddress == null) {
            courseAddress = new ArrayList<I18NString>();
        }
        return this.courseAddress;
    }

    /**
     * Gets the value of the specialArrangements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialArrangements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialArrangements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getSpecialArrangements() {
        if (specialArrangements == null) {
            specialArrangements = new ArrayList<I18NString>();
        }
        return this.specialArrangements;
    }

}
