//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 09:04:12 AM EEST 
//


package eu.europa.ec.learningopportunities.v0_5_10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}LearningOpportunity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="XsdVersion" use="required" type="{http://ec.europa.eu/LearningOpportunities/v0_5_10}XsdVersionType" />
 *       &lt;attribute name="XsdType" use="required" type="{http://ec.europa.eu/LearningOpportunities/v0_5_10}XsdTypeType" />
 *       &lt;attribute name="DatasourceComment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Incremental" type="{http://ec.europa.eu/LearningOpportunities/v0_5_10}BooleanType" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "learningOpportunity"
})
@XmlRootElement(name = "LearningOpportunities")
public class LearningOpportunities {

    @XmlElement(name = "LearningOpportunity", required = true)
    protected List<LearningOpportunity> learningOpportunity;
    @XmlAttribute(name = "Key", required = true)
    protected String key;
    @XmlAttribute(name = "XsdVersion", required = true)
    protected String xsdVersion;
    @XmlAttribute(name = "XsdType", required = true)
    protected XsdTypeType xsdType;
    @XmlAttribute(name = "DatasourceComment")
    protected String datasourceComment;
    @XmlAttribute(name = "Incremental")
    protected String incremental;

    /**
     * Gets the value of the learningOpportunity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the learningOpportunity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLearningOpportunity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LearningOpportunity }
     * 
     * 
     */
    public List<LearningOpportunity> getLearningOpportunity() {
        if (learningOpportunity == null) {
            learningOpportunity = new ArrayList<LearningOpportunity>();
        }
        return this.learningOpportunity;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the xsdVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsdVersion() {
        return xsdVersion;
    }

    /**
     * Sets the value of the xsdVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsdVersion(String value) {
        this.xsdVersion = value;
    }

    /**
     * Gets the value of the xsdType property.
     * 
     * @return
     *     possible object is
     *     {@link XsdTypeType }
     *     
     */
    public XsdTypeType getXsdType() {
        return xsdType;
    }

    /**
     * Sets the value of the xsdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdTypeType }
     *     
     */
    public void setXsdType(XsdTypeType value) {
        this.xsdType = value;
    }

    /**
     * Gets the value of the datasourceComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasourceComment() {
        return datasourceComment;
    }

    /**
     * Sets the value of the datasourceComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasourceComment(String value) {
        this.datasourceComment = value;
    }

    /**
     * Gets the value of the incremental property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncremental() {
        if (incremental == null) {
            return "false";
        } else {
            return incremental;
        }
    }

    /**
     * Sets the value of the incremental property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncremental(String value) {
        this.incremental = value;
    }

}
