//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 09:04:12 AM EEST 
//


package eu.europa.ec.learningopportunities.v0_5_10;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.ec.learningopportunities.v0_5_10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Description_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "Description");
    private final static QName _Costs_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "Costs");
    private final static QName _AccessRequirements_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "AccessRequirements");
    private final static QName _ProviderContactInfo_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "ProviderContactInfo");
    private final static QName _CourseAddress_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "CourseAddress");
    private final static QName _NqfLevel_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "NqfLevel");
    private final static QName _MoreInfo_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "MoreInfo");
    private final static QName _CourseLocationInfo_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "CourseLocationInfo");
    private final static QName _Url_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "Url");
    private final static QName _StartDate_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "StartDate");
    private final static QName _QualificationAwardedDescription_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "QualificationAwardedDescription");
    private final static QName _AdmissionProcedure_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "AdmissionProcedure");
    private final static QName _NonPreferredTerm_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "NonPreferredTerm");
    private final static QName _QualificationAwarded_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "QualificationAwarded");
    private final static QName _CountryCode_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "CountryCode");
    private final static QName _AwardingBody_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "AwardingBody");
    private final static QName _StudyType_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "StudyType");
    private final static QName _DurationCode_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "DurationCode");
    private final static QName _LearningOpportunityId_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "LearningOpportunityId");
    private final static QName _Title_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "Title");
    private final static QName _AwardingBodyContactInfo_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "AwardingBodyContactInfo");
    private final static QName _Grants_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "Grants");
    private final static QName _EducationLevel_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "EducationLevel");
    private final static QName _AwardingBodyUrl_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "AwardingBodyUrl");
    private final static QName _SpecialArrangements_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "SpecialArrangements");
    private final static QName _InformationLanguage_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "InformationLanguage");
    private final static QName _ProviderName_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "ProviderName");
    private final static QName _Credits_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "Credits");
    private final static QName _EqfLevel_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "EqfLevel");
    private final static QName _OtherQualificationAwardedTerm_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "OtherQualificationAwardedTerm");
    private final static QName _DurationInformation_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "DurationInformation");
    private final static QName _ProviderType_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "ProviderType");
    private final static QName _TeachingLanguage_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "TeachingLanguage");
    private final static QName _SpecialTargetGroup_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "SpecialTargetGroup");
    private final static QName _QualificationAwardedURL_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "QualificationAwardedURL");
    private final static QName _ThematicAreasThematicAreas1997_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "ThematicAreas1997");
    private final static QName _ThematicAreasThematicAreas2013_QNAME = new QName("http://ec.europa.eu/LearningOpportunities/v0_5_10", "ThematicAreas2013");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.ec.learningopportunities.v0_5_10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link I18NString }
     * 
     */
    public I18NString createI18NString() {
        return new I18NString();
    }

    /**
     * Create an instance of {@link I18NNonEmptyString }
     * 
     */
    public I18NNonEmptyString createI18NNonEmptyString() {
        return new I18NNonEmptyString();
    }

    /**
     * Create an instance of {@link LearningOpportunities }
     * 
     */
    public LearningOpportunities createLearningOpportunities() {
        return new LearningOpportunities();
    }

    /**
     * Create an instance of {@link LearningOpportunity }
     * 
     */
    public LearningOpportunity createLearningOpportunity() {
        return new LearningOpportunity();
    }

    /**
     * Create an instance of {@link I18NUrl }
     * 
     */
    public I18NUrl createI18NUrl() {
        return new I18NUrl();
    }

    /**
     * Create an instance of {@link ThematicAreas }
     * 
     */
    public ThematicAreas createThematicAreas() {
        return new ThematicAreas();
    }

    /**
     * Create an instance of {@link Qualifications }
     * 
     */
    public Qualifications createQualifications() {
        return new Qualifications();
    }

    /**
     * Create an instance of {@link CourseLocation }
     * 
     */
    public CourseLocation createCourseLocation() {
        return new CourseLocation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "Description")
    public JAXBElement<I18NNonEmptyString> createDescription(I18NNonEmptyString value) {
        return new JAXBElement<I18NNonEmptyString>(_Description_QNAME, I18NNonEmptyString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "Costs")
    public JAXBElement<I18NString> createCosts(I18NString value) {
        return new JAXBElement<I18NString>(_Costs_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "AccessRequirements")
    public JAXBElement<I18NString> createAccessRequirements(I18NString value) {
        return new JAXBElement<I18NString>(_AccessRequirements_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "ProviderContactInfo")
    public JAXBElement<I18NString> createProviderContactInfo(I18NString value) {
        return new JAXBElement<I18NString>(_ProviderContactInfo_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "CourseAddress")
    public JAXBElement<I18NString> createCourseAddress(I18NString value) {
        return new JAXBElement<I18NString>(_CourseAddress_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "NqfLevel")
    public JAXBElement<String> createNqfLevel(String value) {
        return new JAXBElement<String>(_NqfLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "MoreInfo")
    public JAXBElement<I18NNonEmptyString> createMoreInfo(I18NNonEmptyString value) {
        return new JAXBElement<I18NNonEmptyString>(_MoreInfo_QNAME, I18NNonEmptyString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "CourseLocationInfo")
    public JAXBElement<I18NString> createCourseLocationInfo(I18NString value) {
        return new JAXBElement<I18NString>(_CourseLocationInfo_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NUrl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "Url")
    public JAXBElement<I18NUrl> createUrl(I18NUrl value) {
        return new JAXBElement<I18NUrl>(_Url_QNAME, I18NUrl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "StartDate")
    public JAXBElement<I18NString> createStartDate(I18NString value) {
        return new JAXBElement<I18NString>(_StartDate_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "QualificationAwardedDescription")
    public JAXBElement<I18NString> createQualificationAwardedDescription(I18NString value) {
        return new JAXBElement<I18NString>(_QualificationAwardedDescription_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "AdmissionProcedure")
    public JAXBElement<I18NString> createAdmissionProcedure(I18NString value) {
        return new JAXBElement<I18NString>(_AdmissionProcedure_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "NonPreferredTerm")
    public JAXBElement<I18NNonEmptyString> createNonPreferredTerm(I18NNonEmptyString value) {
        return new JAXBElement<I18NNonEmptyString>(_NonPreferredTerm_QNAME, I18NNonEmptyString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "QualificationAwarded")
    public JAXBElement<I18NString> createQualificationAwarded(I18NString value) {
        return new JAXBElement<I18NString>(_QualificationAwarded_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "CountryCode")
    public JAXBElement<String> createCountryCode(String value) {
        return new JAXBElement<String>(_CountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "AwardingBody")
    public JAXBElement<I18NString> createAwardingBody(I18NString value) {
        return new JAXBElement<I18NString>(_AwardingBody_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudyTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "StudyType")
    public JAXBElement<StudyTypeType> createStudyType(StudyTypeType value) {
        return new JAXBElement<StudyTypeType>(_StudyType_QNAME, StudyTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "DurationCode")
    public JAXBElement<String> createDurationCode(String value) {
        return new JAXBElement<String>(_DurationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "LearningOpportunityId")
    public JAXBElement<String> createLearningOpportunityId(String value) {
        return new JAXBElement<String>(_LearningOpportunityId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "Title")
    public JAXBElement<I18NNonEmptyString> createTitle(I18NNonEmptyString value) {
        return new JAXBElement<I18NNonEmptyString>(_Title_QNAME, I18NNonEmptyString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "AwardingBodyContactInfo")
    public JAXBElement<I18NString> createAwardingBodyContactInfo(I18NString value) {
        return new JAXBElement<I18NString>(_AwardingBodyContactInfo_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "Grants")
    public JAXBElement<I18NString> createGrants(I18NString value) {
        return new JAXBElement<I18NString>(_Grants_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "EducationLevel")
    public JAXBElement<String> createEducationLevel(String value) {
        return new JAXBElement<String>(_EducationLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NUrl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "AwardingBodyUrl")
    public JAXBElement<I18NUrl> createAwardingBodyUrl(I18NUrl value) {
        return new JAXBElement<I18NUrl>(_AwardingBodyUrl_QNAME, I18NUrl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "SpecialArrangements")
    public JAXBElement<I18NString> createSpecialArrangements(I18NString value) {
        return new JAXBElement<I18NString>(_SpecialArrangements_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "InformationLanguage")
    public JAXBElement<LanguageCode> createInformationLanguage(LanguageCode value) {
        return new JAXBElement<LanguageCode>(_InformationLanguage_QNAME, LanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "ProviderName")
    public JAXBElement<I18NNonEmptyString> createProviderName(I18NNonEmptyString value) {
        return new JAXBElement<I18NNonEmptyString>(_ProviderName_QNAME, I18NNonEmptyString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "Credits")
    public JAXBElement<I18NString> createCredits(I18NString value) {
        return new JAXBElement<I18NString>(_Credits_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "EqfLevel")
    public JAXBElement<BigInteger> createEqfLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_EqfLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "OtherQualificationAwardedTerm")
    public JAXBElement<I18NString> createOtherQualificationAwardedTerm(I18NString value) {
        return new JAXBElement<I18NString>(_OtherQualificationAwardedTerm_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "DurationInformation")
    public JAXBElement<I18NString> createDurationInformation(I18NString value) {
        return new JAXBElement<I18NString>(_DurationInformation_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "ProviderType")
    public JAXBElement<I18NString> createProviderType(I18NString value) {
        return new JAXBElement<I18NString>(_ProviderType_QNAME, I18NString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "TeachingLanguage")
    public JAXBElement<LanguageCode> createTeachingLanguage(LanguageCode value) {
        return new JAXBElement<LanguageCode>(_TeachingLanguage_QNAME, LanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecialTargetGroupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "SpecialTargetGroup")
    public JAXBElement<SpecialTargetGroupType> createSpecialTargetGroup(SpecialTargetGroupType value) {
        return new JAXBElement<SpecialTargetGroupType>(_SpecialTargetGroup_QNAME, SpecialTargetGroupType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NUrl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "QualificationAwardedURL")
    public JAXBElement<I18NUrl> createQualificationAwardedURL(I18NUrl value) {
        return new JAXBElement<I18NUrl>(_QualificationAwardedURL_QNAME, I18NUrl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "ThematicAreas1997", scope = ThematicAreas.class)
    public JAXBElement<String> createThematicAreasThematicAreas1997(String value) {
        return new JAXBElement<String>(_ThematicAreasThematicAreas1997_QNAME, String.class, ThematicAreas.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", name = "ThematicAreas2013", scope = ThematicAreas.class)
    public JAXBElement<String> createThematicAreasThematicAreas2013(String value) {
        return new JAXBElement<String>(_ThematicAreasThematicAreas2013_QNAME, String.class, ThematicAreas.class, value);
    }

}
