//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 09:04:12 AM EEST 
//


package eu.europa.ec.learningopportunities.v0_5_10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}QualificationAwarded" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}OtherQualificationAwardedTerm" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}QualificationAwardedURL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}QualificationAwardedDescription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}AwardingBody" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}AwardingBodyContactInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ec.europa.eu/LearningOpportunities/v0_5_10}AwardingBodyUrl" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qualificationAwarded",
    "otherQualificationAwardedTerm",
    "qualificationAwardedURL",
    "qualificationAwardedDescription",
    "awardingBody",
    "awardingBodyContactInfo",
    "awardingBodyUrl"
})
@XmlRootElement(name = "Qualifications")
public class Qualifications {

    @XmlElement(name = "QualificationAwarded", required = true)
    protected List<I18NString> qualificationAwarded;
    @XmlElement(name = "OtherQualificationAwardedTerm")
    protected List<I18NString> otherQualificationAwardedTerm;
    @XmlElement(name = "QualificationAwardedURL")
    protected List<I18NUrl> qualificationAwardedURL;
    @XmlElement(name = "QualificationAwardedDescription")
    protected List<I18NString> qualificationAwardedDescription;
    @XmlElement(name = "AwardingBody")
    protected List<I18NString> awardingBody;
    @XmlElement(name = "AwardingBodyContactInfo")
    protected List<I18NString> awardingBodyContactInfo;
    @XmlElement(name = "AwardingBodyUrl")
    protected List<I18NUrl> awardingBodyUrl;

    /**
     * Gets the value of the qualificationAwarded property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationAwarded property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationAwarded().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getQualificationAwarded() {
        if (qualificationAwarded == null) {
            qualificationAwarded = new ArrayList<I18NString>();
        }
        return this.qualificationAwarded;
    }

    /**
     * Gets the value of the otherQualificationAwardedTerm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherQualificationAwardedTerm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherQualificationAwardedTerm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getOtherQualificationAwardedTerm() {
        if (otherQualificationAwardedTerm == null) {
            otherQualificationAwardedTerm = new ArrayList<I18NString>();
        }
        return this.otherQualificationAwardedTerm;
    }

    /**
     * Gets the value of the qualificationAwardedURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationAwardedURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationAwardedURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NUrl }
     * 
     * 
     */
    public List<I18NUrl> getQualificationAwardedURL() {
        if (qualificationAwardedURL == null) {
            qualificationAwardedURL = new ArrayList<I18NUrl>();
        }
        return this.qualificationAwardedURL;
    }

    /**
     * Gets the value of the qualificationAwardedDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationAwardedDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationAwardedDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getQualificationAwardedDescription() {
        if (qualificationAwardedDescription == null) {
            qualificationAwardedDescription = new ArrayList<I18NString>();
        }
        return this.qualificationAwardedDescription;
    }

    /**
     * Gets the value of the awardingBody property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awardingBody property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAwardingBody().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getAwardingBody() {
        if (awardingBody == null) {
            awardingBody = new ArrayList<I18NString>();
        }
        return this.awardingBody;
    }

    /**
     * Gets the value of the awardingBodyContactInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awardingBodyContactInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAwardingBodyContactInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NString }
     * 
     * 
     */
    public List<I18NString> getAwardingBodyContactInfo() {
        if (awardingBodyContactInfo == null) {
            awardingBodyContactInfo = new ArrayList<I18NString>();
        }
        return this.awardingBodyContactInfo;
    }

    /**
     * Gets the value of the awardingBodyUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awardingBodyUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAwardingBodyUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link I18NUrl }
     * 
     * 
     */
    public List<I18NUrl> getAwardingBodyUrl() {
        if (awardingBodyUrl == null) {
            awardingBodyUrl = new ArrayList<I18NUrl>();
        }
        return this.awardingBodyUrl;
    }

}
