//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 09:04:12 AM EEST 
//


package eu.europa.ec.learningopportunities.v0_5_10;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StudyTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StudyTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FT"/>
 *     &lt;enumeration value="PT"/>
 *     &lt;enumeration value="FF"/>
 *     &lt;enumeration value="DL"/>
 *     &lt;enumeration value="ON"/>
 *     &lt;enumeration value="BL"/>
 *     &lt;enumeration value="WK"/>
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="TR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StudyTypeType")
@XmlEnum
public enum StudyTypeType {

    FT,
    PT,
    FF,
    DL,
    ON,
    BL,
    WK,
    AP,
    TR;

    public String value() {
        return name();
    }

    public static StudyTypeType fromValue(String v) {
        return valueOf(v);
    }

}
