//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 09:04:12 AM EEST 
//


package eu.europa.ec.learningopportunities.v0_5_10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ThematicAreas1997" type="{http://ec.europa.eu/LearningOpportunities/v0_5_10}ThematicAreasType1997"/>
 *         &lt;element name="ThematicAreas2013" type="{http://ec.europa.eu/LearningOpportunities/v0_5_10}ThematicAreasType2013"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "thematicAreas1997OrThematicAreas2013"
})
@XmlRootElement(name = "ThematicAreas")
public class ThematicAreas {

    @XmlElementRefs({
        @XmlElementRef(name = "ThematicAreas2013", namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ThematicAreas1997", namespace = "http://ec.europa.eu/LearningOpportunities/v0_5_10", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> thematicAreas1997OrThematicAreas2013;

    /**
     * Gets the value of the thematicAreas1997OrThematicAreas2013 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thematicAreas1997OrThematicAreas2013 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThematicAreas1997OrThematicAreas2013().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getThematicAreas1997OrThematicAreas2013() {
        if (thematicAreas1997OrThematicAreas2013 == null) {
            thematicAreas1997OrThematicAreas2013 = new ArrayList<JAXBElement<String>>();
        }
        return this.thematicAreas1997OrThematicAreas2013;
    }

}
