package fi.vm.sade.model;

public final class KoulutusAsteTyyppi {
    public static final String AMMATILLINEN_PERUSTUTKINTO = "AMMATILLINEN_PERUSTUTKINTO";
    public static final String AMMATTITUTKINTO = "AMMATTITUTKINTO";
    public static final String ERIKOISAMMATTITUTKINTO = "ERIKOISAMMATTITUTKINTO";
    public static final String KORKEAKOULUTUS = "KORKEAKOULUTUS";
    public static final String AMM_OHJAAVA_JA_VALMISTAVA_KOULUTUS = "AMM_OHJAAVA_JA_VALMISTAVA_KOULUTUS";
    public static final String LUKIOKOULUTUS = "LUKIOKOULUTUS";
    public static final String MAAHANM_AMM_VALMISTAVA_KOULUTUS = "MAAHANM_AMM_VALMISTAVA_KOULUTUS";
    public static final String TUNTEMATON = "TUNTEMATON";
    public static final String VALMENTAVA_JA_KUNTOUTTAVA_OPETUS = "VALMENTAVA_JA_KUNTOUTTAVA_OPETUS";
    public static final String VAPAAN_SIVISTYSTYON_KOULUTUS = "VAPAAN_SIVISTYSTYON_KOULUTUS";
    public static final String PERUSOPETUKSEN_LISAOPETUS = "PERUSOPETUKSEN_LISAOPETUS";
    public static final String MAAHANM_LUKIO_VALMISTAVA_KOULUTUS = "MAAHANM_LUKIO_VALMISTAVA_KOULUTUS";
}
